import React, { useState, useEffect } from 'react';
import API from '../../api/config';

// --- CONFIGURATION FOR PRINTING ---
const HOSPITAL_DETAILS = {
  name: "EasyCare Hospital",
  address: "123 Health Avenue, Medical District, Jhang",
  phone: "+92 123 456 7890",
  email: "easycare@gmail.com",
  logoUrl: "https://via.placeholder.com/150?text=H+Logo" 
};

const TestReportHistoryTab = ({ data = [], patientId }) => {
  const [reports, setReports] = useState(data);
  const [deletingId, setDeletingId] = useState(null);

  useEffect(() => {
    setReports(data);
  }, [data]);

  // --- ENHANCED PRINT FUNCTION ---
  const handlePrintSingle = (report) => {
    const printWindow = window.open('', '', 'width=900,height=800');
    
    // We create a dedicated HTML structure for printing to ensure it looks like a real document
    // regardless of the screen size or UI theme.
    const htmlContent = `
      <html>
        <head>
          <title>Medical Report - ${report.Report_ID}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #333; max-width: 800px; margin: 0 auto; }
            .header { border-bottom: 2px solid #0891b2; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
            .hospital-name { font-size: 24px; font-weight: bold; color: #0891b2; text-transform: uppercase; margin: 0; }
            .hospital-details { font-size: 12px; color: #666; margin-top: 5px; }
            .report-meta { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; background: #f8fafc; padding: 15px; border-radius: 8px; border: 1px solid #e2e8f0; }
            .meta-group { display: flex; flex-direction: column; }
            .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; font-weight: 600; }
            .value { font-size: 14px; font-weight: 500; color: #0f172a; }
            .content-box { margin-bottom: 40px; }
            .content-title { font-size: 16px; font-weight: bold; color: #334155; border-bottom: 1px solid #cbd5e1; padding-bottom: 8px; margin-bottom: 15px; }
            .result-text { font-size: 14px; line-height: 1.6; white-space: pre-wrap; }
            .footer { border-top: 1px solid #e2e8f0; padding-top: 20px; margin-top: 50px; text-align: center; font-size: 10px; color: #94a3b8; }
            .signature { margin-top: 60px; display: flex; justify-content: flex-end; }
            .sign-line { border-top: 1px solid #333; width: 200px; text-align: center; padding-top: 5px; font-size: 12px; font-weight: bold; }
            
            @media print {
              body { padding: 0; }
              @page { margin: 2cm; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <h1 class="hospital-name">${HOSPITAL_DETAILS.name}</h1>
              <div class="hospital-details">
                ${HOSPITAL_DETAILS.address}<br>
                ${HOSPITAL_DETAILS.phone} | ${HOSPITAL_DETAILS.email}
              </div>
            </div>
            </div>

          <div class="report-meta">
            <div class="meta-group">
              <span class="label">Patient ID</span>
              <span class="value">${patientId || 'N/A'}</span>
            </div>
            <div class="meta-group">
              <span class="label">Report ID</span>
              <span class="value">#${report.Report_ID}</span>
            </div>
            <div class="meta-group">
              <span class="label">Report Type</span>
              <span class="value">${report.Type || 'General Lab Report'}</span>
            </div>
            <div class="meta-group">
              <span class="label">Date Generated</span>
              <span class="value">${new Date(report.Date).toLocaleDateString("en-GB", { weekday: 'long', year: "numeric", month: "long", day: "numeric" })}</span>
            </div>
          </div>

          <div class="content-box">
            <h2 class="content-title">Report Findings & Summary</h2>
            <div class="result-text">
              ${report.Result_Summary || report.Result || "No detailed summary available."}
            </div>
          </div>

          <div class="signature">
            <div class="sign-line">Authorized Pathologist / Doctor</div>
          </div>

          <div class="footer">
            <p>This is a computer-generated report. If there are any discrepancies, please contact the laboratory immediately.</p>
            <p>Generated by ${HOSPITAL_DETAILS.name} Laboratory Information System</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    
    // Wait for content to load before printing (important for images/fonts)
    printWindow.onload = function() {
      printWindow.focus();
      printWindow.print();
      // Optional: printWindow.close(); // Keep open to let user confirm
    };
  };

  const handleDelete = async (reportId) => {
    if (!window.confirm("Are you sure you want to permanently delete this medical record?")) return;
    setDeletingId(reportId);
    try {
      await API.delete(`/reports/${reportId}`);
      setReports((prev) => prev.filter((r) => r.Report_ID !== reportId));
    } catch (err) {
      alert("System Error: Could not delete report. Please try again.");
    } finally {
      setDeletingId(null);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto p-4 bg-gray-50/50 min-h-full font-sans">
      {/* Page Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h4 className="font-bold text-xl text-slate-800">Lab Reports History</h4>
          <p className="text-sm text-slate-500 mt-1">
            Viewing records for Patient ID: <span className="font-mono text-slate-700 bg-slate-100 px-1 rounded">{patientId}</span>
          </p>
        </div>
        <div className="bg-white px-3 py-1 rounded border border-slate-200 shadow-sm">
          <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Total Reports</span>
          <div className="text-lg font-bold text-cyan-700 text-center">{reports.length}</div>
        </div>
      </div>

      {reports.length === 0 ? (
        <div className="flex flex-col items-center justify-center p-12 bg-white rounded-xl shadow-sm border border-dashed border-slate-300">
          <div className="w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center mb-4">
             <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-slate-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
               <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
             </svg>
          </div>
          <p className="text-slate-600 font-medium">No test reports available</p>
          <p className="text-slate-400 text-xs mt-1">New reports will appear here once generated.</p>
        </div>
      ) : (
        <div className="grid gap-4 sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1">
          {reports.map((r) => (
            <div
              key={r.Report_ID}
              className="group bg-white rounded-lg shadow-sm border border-slate-200 hover:shadow-md transition-shadow duration-200 overflow-hidden"
            >
              {/* Card Header with Colored Strip */}
              <div className="h-1 w-full bg-cyan-600"></div>
              
              <div className="p-4 sm:p-5 flex flex-col sm:flex-row gap-4">
                
                {/* Left: Date Box */}
                <div className="flex-shrink-0 flex flex-row sm:flex-col items-center justify-center bg-slate-50 border border-slate-100 rounded p-2 sm:w-20 text-center gap-2 sm:gap-0">
                  <span className="text-xs font-bold text-slate-400 uppercase">
                    {new Date(r.Date).toLocaleDateString("en-GB", { month: "short" })}
                  </span>
                  <span className="text-xl sm:text-2xl font-bold text-slate-700 leading-none">
                    {new Date(r.Date).getDate()}
                  </span>
                  <span className="text-[10px] text-slate-400">
                    {new Date(r.Date).getFullYear()}
                  </span>
                </div>

                {/* Middle: Content */}
                <div className="flex-grow">
                   <div className="flex items-start justify-between">
                      <div>
                        <h2 className="text-base font-bold text-slate-800 flex items-center gap-2">
                          {r.Type || "Medical Report"}
                          <span className="text-[10px] bg-slate-100 text-slate-500 px-1.5 py-0.5 rounded border border-slate-200 font-mono">
                            #{r.Report_ID}
                          </span>
                        </h2>
                      </div>
                   </div>
                   
                   <div className="mt-3">
                      <p className="text-xs font-bold text-slate-400 uppercase mb-1">Clinical Findings</p>
                      <p className="text-sm text-slate-600 leading-relaxed line-clamp-2">
                        {r.Result_Summary || r.Result || "No detailed summary recorded."}
                      </p>
                   </div>
                </div>

                {/* Right: Actions */}
                <div className="flex sm:flex-col items-center justify-center sm:justify-start gap-2 sm:pl-4 sm:border-l sm:border-slate-100 pt-4 sm:pt-0 border-t sm:border-t-0 border-slate-100 mt-2 sm:mt-0 w-full sm:w-auto">
                  <button
                    onClick={() => handlePrintSingle(r)}
                    className="flex-1 sm:flex-none w-full flex items-center justify-center gap-2 px-4 py-2 bg-cyan-50 text-cyan-700 hover:bg-cyan-100 rounded text-xs font-semibold transition-colors"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                    </svg>
                    Print
                  </button>
                  
                  <button
                    onClick={() => handleDelete(r.Report_ID)}
                    disabled={deletingId === r.Report_ID}
                    className="flex-1 sm:flex-none w-full flex items-center justify-center gap-2 px-4 py-2 bg-white text-rose-600 border border-rose-100 hover:bg-rose-50 rounded text-xs font-semibold transition-colors"
                  >
                     {deletingId === r.Report_ID ? (
                        <span className="animate-spin h-3 w-3 border-2 border-rose-600 border-t-transparent rounded-full"></span>
                      ) : (
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                      )}
                    Delete
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default TestReportHistoryTab;